// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: refreshtokens.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const makeRefreshToken = `-- name: MakeRefreshToken :exec
INSERT INTO refresh_tokens(token, created_at, updated_at, user_id, expires_at)
VALUES(
    $1,
    NOW(),
    NOW(),
    $2,
    NOW() + INTERVAL '60 DAYS'
)
`

type MakeRefreshTokenParams struct {
	Token  string
	UserID uuid.UUID
}

func (q *Queries) MakeRefreshToken(ctx context.Context, arg MakeRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, makeRefreshToken, arg.Token, arg.UserID)
	return err
}
